add shellcheck and shfmt checks

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -43,3 +43,29 @@ jobs:
 
       - name: Run mypy typecheck
         run: uv run mypy --pretty -- app
+
+      - name: Run shfmt
+        run: |
+          globalStatus=0
+
+          while IFS= read -r -d '' f; do
+            if ! uv run shfmt --diff --indent 4 -- "$f"; then
+              echo "[ERROR] shfmt failed for $f"
+              globalStatus=1
+            fi
+          done < <(find .hooks scripts -type f -name '*.sh' -print0)
+
+          exit $globalStatus
+
+      - name: Run shellcheck
+        run: |
+          globalStatus=0
+
+          while IFS= read -r -d '' f; do
+            if ! uv run shellcheck --external-sources --exclude=SC2034 -- "$f"; then
+              echo "[ERROR] shellcheck failed for $f"
+              globalStatus=1
+            fi
+          done < <(find .hooks scripts -type f -name '*.sh' -print0)
+
+          exit $globalStatus
